### ISSUE TITLE
"MemoryError" on rocket

### ISSUE THREAD

**Issue by tyevhen** [mt2017-tartu-shared-task/nmt-system-E#1]
We ran the following code and got:
Traceback (most recent call last):
  File "/gpfs/hpchome/yevhen/nmt-system-E/OpenNMT-py/tools/subword-nmt/learn_bpe.py", line 250, in <module>
    main(args.input, args.output, args.symbols, args.min_frequency, args.verbose, is_dict=args.dict_input)
  File "/gpfs/hpchome/yevhen/nmt-system-E/OpenNMT-py/tools/subword-nmt/learn_bpe.py", line 226, in main
    prune_stats(stats, big_stats, threshold)
  File "/gpfs/hpchome/yevhen/nmt-system-E/OpenNMT-py/tools/subword-nmt/learn_bpe.py", line 183, in prune_stats
    big_stats[item] = freq
MemoryError

[script.txt](https://github.com/mt2017-tartu-shared-task/nmt-system-E/files/1346598/script.txt)

We faced this problem on BPE applying stage.  How it can be tackled?

**Comment by MaksymDel** [comment]
It is not a good idea to run your job directly on headnode of rocket cluster. You can read about it more on the same website SLURM docs are stored.  The University of Tartu has 100+ specialized CPU servers to run user jobs, to use it just create SLURM sripts. So:

1. You should run all your scripts (both **CPU** and **GPU**) with **SLURM**. Corresponding pdf documents are updated.  

2. I suggest creating one script per command. 
 
3. See also this  [issue](https://github.com/mt2017-tartu-shared-task/nmt-system-D/issues/1).

4. I suggest using 50.000 sentences for the test set, and 25.000 for the dev set. This way you will get acceptable results faster (classical 70-10-20% Machine Learning split is not suitable for that big datasets).

@mt2017-tartu-shared-task/imperium
@mt2017-tartu-shared-task/mali
@mt2017-tartu-shared-task/powerrangers
@mt2017-tartu-shared-task/quidditchchampions
@mt2017-tartu-shared-task/researchers
@mt2017-tartu-shared-task/toneko
@fishel @maxdel

**Comment by MaksymDel** [comment]
Hi,

did it solve your problem? If so, you can close the issue.
