### ISSUE TITLE
Sockeye train

### ISSUE THREAD

**Issue by dimatkachuk** [mt2017-tartu-shared-task/nmt-system-E#11]
Hi. 
My team faced the problem with sockeye training. We have tried this approach:
module load python-3.6.0
python -m sockeye.train -s bpe.cl-tc-tok-train.et \ ...

But it gave us such mistake:

Traceback (most recent call last):
  File "/storage/software/python-3.6.0/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/storage/software/python-3.6.0/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/storage/software/python-3.6.0/lib/python3.6/site-packages/sockeye/train.py", line 26, in <module>
    import mxnet as mx
  File "/storage/software/python-3.6.0/lib/python3.6/site-packages/mxnet/__init__.py", line 25, in <module>
    from .base import MXNetError
  File "/storage/software/python-3.6.0/lib/python3.6/site-packages/mxnet/base.py", line 111, in <module>
    _LIB = _load_lib()
  File "/storage/software/python-3.6.0/lib/python3.6/site-packages/mxnet/base.py", line 103, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/storage/software/python-3.6.0/lib/python3.6/ctypes/__init__.py", line 344, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcuda.so.1: cannot open shared object file: No such file or directory

**Comment by MaksymDel** [comment]
Please provide your slurm .sh file

**Comment by dimatkachuk** [comment]
Our slurp bash script is follows:


#!/bin/bash

#The name of the job is
#SBATCH -J nmt_power_rangers_task

#The job requires 1 compute node
#SBATCH -N 1

#The job requires 1 task per node
#SBATCH --ntasks-per-node=1

#The maximum walltime of the job is a 8 days
#SBATCH -t 192:00:00

#SBATCH --mail-type=ALL
#SBATCH --mail-user=dimatkachukgf@gmail.com

#SBATCH --mem=50G

#Leave this here if you need a GPU for your job
#SBATCH --partition=gpu
#SBATCH --gres=gpu:tesla:1

module load python-3.6.0

echo 'started'

python -m sockeye.train -s bpe.cl-tc-tok-train.et \
                                     -t bpe.cl-tc-tok-train.en \
                                     -vs bpe.cl-tc-tok-dev.et \
                                     -vt bpe.cl-tc-tok-dev.en \
                                     --num-embed 256 \
                                     --rnn-num-hidden 512 \
                                     --rnn-attention-type dot \
                                     --max-seq-len 60 \
                                     --monitor-bleu 500 \
                                     -o ./model/

**Comment by MaksymDel** [comment]
This error occurs when you try to execute `import mxnet` on CPU (Sockeye is written in mxnet). But your bash script tells that you are requesting GPU, and `import mxnet` definitely should work on falcons.

Feels like hpc problem. Please write to support@hpc.ut.ee, include your error, slurm script, and my comment above.

**Comment by dimatkachuk** [comment]
Okay. Thank you. I'll try it.
