### ISSUE TITLE
Problems with rocket.

### ISSUE THREAD

**Issue by dimatkachuk** [mt2017-tartu-shared-task/nmt-system-E#12]
Hi! 

My sockeye model has finished training but I can't evaluate its translation, as I have next issue:

Last login: Thu Dec 14 22:03:53 on ttys002
MBP-Dima:~ dima$ ssh dmytro95@rocket.hpc.ut.ee
ssh: connect to host rocket.hpc.ut.ee port 22: Operation timed out
MBP-Dima:~ dima$ ssh dmytro95@rocket.hpc.ut.ee
ssh: connect to host rocket.hpc.ut.ee port 22: Operation timed out

I will try later, maybe rocket will answer me, but if not, is it possible to update our README after deadline?

**Comment by MaksymDel** [comment]
Rocket is responding now. 

Also, in your readme, please use `<br>` to make a new line, and be more specific about what changes you applied (e.g. instead of `dropout`, use `dropout = 0.5`)

**Comment by tyevhen** [comment]
Ok, we will fix this.

**Comment by dimatkachuk** [comment]
Fixed.
