### ISSUE TITLE
Test set BLEU

### ISSUE THREAD

**Issue by MaksymDel** [mt2017-tartu-shared-task/nmt-system-E#14]
Hi guys, 

as I understand you decided to call your final translations file `de_toc.de_tc.de_bpe.hyps.en`

No problem, but it gives only 9.99 BLEU. 

Any comments on this?

**Comment by dimatkachuk** [comment]
Hello. I have added a new translated test file in folder with name test-final-2. Can you evaluate it?

**Comment by MaksymDel** [comment]
Hi, sure, I will let you know.

**Comment by MaksymDel** [comment]
BLEU = 25.60
