### ISSUE TITLE
Connection to server falcon1 or falcon2

### ISSUE THREAD

**Issue by dimatkachuk** [mt2017-tartu-shared-task/nmt-system-E#2]
Hi.
Can you remember how to connect to falcon1 or falcon2?

**Comment by MaksymDel** [comment]
Hi, 

first, ssh to rocket. Second, execute `ssh falcon1` or `ssh falcon2`.

However, if you do something using big data, you should use SLURM (for this you do not need connect to falcons at all).

**Comment by dimatkachuk** [comment]
Thank you.
