### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tyevhen** [mt2017-tartu-shared-task/nmt-system-E#3]
Preparing training ...
Traceback (most recent call last):
  File "/gpfs/hpchome/yevhen/nmt-system-E/OpenNMT-py/preprocess.py", line 78, in <module>
    main()
  File "/gpfs/hpchome/yevhen/nmt-system-E/OpenNMT-py/preprocess.py", line 56, in main
    _, _, nFeatures = onmt.IO.extract_features(src_line)
  File "/gpfs/hpchome/yevhen/nmt-system-E/OpenNMT-py/onmt/IO.py", line 35, in extract_features
    token_size = len(split_tokens[0])
IndexError: list index out of range

Got this type of error while building vocabulary from the training set and coverting it into PyTorch format.

Can you suggest some solutions?=)

**Comment by MaksymDel** [comment]
It probably says you have empty lines in your training set. Did you clean your training set with `clean-corpus.perl`?

**Comment by BreakINbaDs** [comment]
After starting from scratch and having  training and dev sets cleaned got the same error during building vocabulary with preprocess.py

**Comment by MaksymDel** [comment]
Please give me your SLURM script for preprocess.py and an address of your data on HPC.

**Comment by BreakINbaDs** [comment]
/gpfs/hpchome/raman94/nmt-system-E/data

#!/bin/bash

#The name of the job is
#SBATCH -J nmt_power_rangers_task

#The job requires 1 compute node
#SBATCH -N 1

#The job requires 1 task per node
#SBATCH --ntasks-per-node=1

#SBATCH --mail-type=ALL
#SBATCH --mail-user=dimatkachukgf@gmail.com

#The maximum walltime of the job is a 1 days
#SBATCH -t 24:00:00

#SBATCH --mem=150G

#SBATCH --partition=gpu
#SBATCH --gres=gpu:tesla:1

module load python-2.7.13
python /gpfs/hpchome/raman94/nmt-system-E/OpenNMT-py/preprocess.py 
-train_src /gpfs/hpchome/raman94/nmt-system-E/data/bpe.cleaned-tc-tok-train.et  
-train_tgt /gpfs/hpchome/raman94/nmt-system-E/data/bpe.cleaned-tc-tok-train.en 
-valid_src /gpfs/hpchome/raman94/nmt-system-E/data/bpe.tc-tok-dev.et  
-valid_tgt /gpfs/hpchome/raman94/nmt-system-E/data/bpe.tc-tok-dev.en 
-save_data /gpfs/hpchome/raman94/nmt-system-E/data/rdy -src_vocab_size 10000 -seed 123

**Comment by MaksymDel** [comment]
Why you  do not specify the tgt vocab size?

**Comment by BreakINbaDs** [comment]
I did that.
Just failed to copy past it in  here

I have in bash :  -tgt_vocab_size 10000

**Comment by MaksymDel** [comment]
Do you experience a memory error with 150G allocated?

**Comment by MaksymDel** [comment]
Sorry, not memory error, but the issue where your job goes to queue: #7
