### ISSUE TITLE
ImportError: No module named site

### ISSUE THREAD

**Issue by tyevhen** [mt2017-tartu-shared-task/nmt-system-E#5]
We got this error after this line in our script:

cat cleaned-tc-tok-train.et cleaned-tc-tok-train.en | /gpfs/hpchome/maksym95/shared-task-2017/OpenNMT-py/tools/subword-nmt/learn_bpe.py -s 10000 > eten.bpe
echo "Done LearnBPE"

What would you recommend in this case?

**Comment by MaksymDel** [comment]
I suggest using BPE scripts that are contained in your own HPC folder, and making sure you executed `module load python-2.7.13` beforehand.

**Comment by tyevhen** [comment]
We definitely executed module load python-2.7.13. 
So, you mean that the BPE  scripts can be different in these folders? I am asking because I considered that these scripts must be same.

**Comment by MaksymDel** [comment]
Your error is unique, no one has encountered it before. Can you please send me a full error message and a full script you use to produce the error (as .txt files)?

BPE scripts are the same, but you have read-only access to my HPC folder and maybe there are some other restrictions, so it is safer to do it just like specified in lab1.pdf.

**Comment by tyevhen** [comment]
[filter.txt](https://github.com/mt2017-tartu-shared-task/nmt-system-E/files/1349779/filter.txt)
[split.txt](https://github.com/mt2017-tartu-shared-task/nmt-system-E/files/1349778/split.txt)
[true_case.txt](https://github.com/mt2017-tartu-shared-task/nmt-system-E/files/1349775/true_case.txt)
[BPE.txt](https://github.com/mt2017-tartu-shared-task/nmt-system-E/files/1349776/BPE.txt)
[cat_all.txt](https://github.com/mt2017-tartu-shared-task/nmt-system-E/files/1349777/cat_all.txt)

**Comment by tyevhen** [comment]
[applyBPE.txt](https://github.com/mt2017-tartu-shared-task/nmt-system-E/files/1349783/applyBPE.txt)

**Comment by MaksymDel** [comment]
You still did not send me a full error message. Random suggestion: try also to execute your command with _python_ at the beginning: `python path_to_your_bpe_scripts/apply_bpe.py`.

Otherwise, you can google this error and try to follow guidelines from the internet. 

The last option would be to do the whole lab on the small data from the beginning, because if done right, it should work

**Comment by tyevhen** [comment]
The full error is "ImportError: No module named site". It was the only error in our .sh file after execution. Ok, we will try that.

**Comment by MaksymDel** [comment]
Do you still have this error? Because other issues of your team have to do with preprocess.py, which is the next step after BPE.
