### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by dimatkachuk** [mt2017-tartu-shared-task/nmt-system-E#7]
I received an error: 
slurmstepd: error: Job 2548697 exceeded memory limit (52445460 > 52428800), being killed
slurmstepd: error: Exceeded job memory limit
slurmstepd: error: *** JOB 2548697 ON falcon2 CANCELLED AT 2017-10-05T13:22:02 ***
slurmstepd: error: Exceeded step memory limit at some point.

I was tried to put memory to 100G, but stands in queue. I got it. But how can I not getting exceeded step memory limit.

**Comment by MaksymDel** [comment]
First of all, it is good to know what command causes an error. What command causes an error in your case?

**Comment by dimatkachuk** [comment]
I put my vocabulary for preprocessing with such script:
#!/bin/bash

#The name of the job is
#SBATCH -J nmt_power_rangers_task

#The job requires 1 compute node
#SBATCH -N 1

#The job requires 1 task per node
#SBATCH --ntasks-per-node=1

#The maximum walltime of the job is a 8 days
#SBATCH -t 192:00:00

#SBATCH --mail-type=ALL
#SBATCH --mail-user=dimatkachukgf@gmail.com

#SBATCH --mem=50G

#Leave this here if you need a GPU for your job
#SBATCH --partition=gpu
#SBATCH --gres=gpu:tesla:1

module load python-2.7.13

python preprocess.py -train_src ../data/bpe_sm.cleaned-tc-tok-train.et -train_tgt ../data/bpe_sm.cleaned-tc-tok-train.en -valid_src ../data/bpe_sm.cleaned-tc-tok-dev.et 
-valid_tgt ../data/bpe_sm.cleaned-tc-tok-dev.en -save_data ../data/rdy
-src_vocab_size 20000
-tgt_vocab_size 20000 -seed 123

echo 'finished'

**Comment by dimatkachuk** [comment]
When I wrote it I referred you script and scripts of other teams. When I get this error first time, I have tried to use another splitting of raw corpora as you advised to us (50000 - 25000 - other). Then I repeat all process and put it again. It gives this error again. So I tried to take 150G of memory, but it gives me that problem that we have discussed.

**Comment by dimatkachuk** [comment]
Then I tried again with 50, and it gave me this error again

**Comment by MaksymDel** [comment]
It is really strange... Try to clone OpenNMT-py in a new folder, and use  preprocess.py from that new OpenNMT-py.

**Comment by MaksymDel** [comment]
I mean you should clone it from the GitHub OpenNMT-py repo. I.e.:

`git clone https://github.com/OpenNMT/OpenNMT-py`

**Comment by dimatkachuk** [comment]
I have tried to run with new copied OpenNMT-py repo. But I haven't succeeded. I chose 50 G, 100G and It gave me the same mistake.
Now it is running on 150G. Need to wait.

**Comment by MaksymDel** [comment]
So it is running, cool! But do you experience #3 ?

**Comment by MaksymDel** [comment]
And did you **copy** OpenNMT-py from my HPC folder, or **clone** it from the internet?

**Comment by dimatkachuk** [comment]
Vocabulary get ready. So I put model to the training. I think there is the last problem with GitHub.
