### ISSUE TITLE
Preprocessing of accurate dev

### ISSUE THREAD

**Issue by dimatkachuk** [mt2017-tartu-shared-task/nmt-system-E#8]
Hi.

I have two questions concerning the preprocessing of accurate dev:

1. After tokenization which was strait forward, I need to apply truecasing. On this stage I need firstly to train truecasing to get model. And I can't get should we train it on accurate dev set as we don't have train set for it, or I should use my model 'et-truecase.mdl' from lab1? 

2. On the stage of bpe, I have the similar question. When I need to learn bpe, should I learn it on accurate dev set, or it's better to take 'eten.bpe' from lab1?
As I understand I should take 'eten.bpe' from lab1, because otherwise learn-bpe.py gives me:
"no pair has frequency >= 2. Stopping" 
Am I right?

**Comment by MaksymDel** [comment]
Thanks for the question!

Think about how (for example) Google Translate service works. Roughly speaking, they had some training parallel corpus, and they built neural as well as some preprocessing models on it. 

Then, when you send them your own sentence to translate, they just apply all the preprocessing based on the models they trained and perform the translation. Last step is the postprocessing, and sending the hyps back to you. 

Dev and test sets are (roughly) to imitate the sentences you send to the translation service. 

So the answer is that you should use the models you trained on the train set. 

@mt2017-tartu-shared-task/imperium
@mt2017-tartu-shared-task/mali
@mt2017-tartu-shared-task/powerrangers
@mt2017-tartu-shared-task/quidditchchampions
@mt2017-tartu-shared-task/researchers
@mt2017-tartu-shared-task/toneko
@fishel @maxdel

**Comment by dimatkachuk** [comment]
We thought the same way but wanted to be sure. 
Thank you.
