### ISSUE TITLE
Comparing our file with accurate dev 

### ISSUE THREAD

**Issue by dimatkachuk** [mt2017-tartu-shared-task/nmt-system-E#9]
According to your answer on issue of group C, we need to make 4 steps, where 3rd step is:
3. Compare your result file from step 2 with the accurate dev.en (compute BLUE) 

For this one I have used such command: 
perl ../OpenNMT-py/tools/multi-bleu.perl dev.en < de_tok.de_tc.de_bpe.hyps.en

Am I right to do so?  Because the score seems to be really low (21.14).

**Comment by MaksymDel** [comment]
The command `perl ../OpenNMT-py/tools/multi-bleu.perl dev.en < de_tok.de_tc.de_bpe.hyps.en` looks ok to me.

**Comment by dimatkachuk** [comment]
Great.
